name: ci/docker Build and Push for Production

on:
  push:
    branches:
      - develop
      - feature/*

env:
  # レジストリ名は適当に変更してください
  REGISTRY_NAME: repository-name
  IMAGE_NAME: expless-template
  BUILD_TAG: dev

jobs:
  build_flow:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Build
        run: docker build -t $IMAGE_NAME:$BUILD_TAG -f ./docker/Dockerfile .

      - name: Tag
        run: docker image tag $IMAGE_NAME:$BUILD_TAG $REGISTRY_NAME/$IMAGE_NAME:$BUILD_TAG

      # - name: Push
      #  run: docker image push $REGISTRY_NAME/$IMAGE_NAME:$BUILD_TAG

  slack_notification:
    runs-on: ubuntu-latest
    if: ${{ secrets.SLACK_WEBHOOK_URL != "" }}
    needs: build_flow

    steps:
      - name: Notify slack - URLs
        if: ${{ ! failure() }}
        run: |
          curl -X POST --data-urlencode "payload={\"text\": \"${{ github.repository }} Deploy to develop\"}" ${{ secrets.SLACK_WEBHOOK_URL }}
          curl -X POST --data-urlencode "payload={\"text\": \"デプロイ対象 : ${{ github.sha }}\"}" ${{ secrets.SLACK_WEBHOOK_URL }}
      - name: Notify slack when failed
        if: ${{ failure() }}
        run: |
          curl -X POST --data-urlencode "payload={\"text\": \"${{ github.repository }}のデプロイに失敗しました\"}" ${{ secrets.SLACK_WEBHOOK_URL }}
